version: '3'
services:
  mongodb:
    # build:
    #   context: serverless-mongo
    image: ${REPO}/rs-mongodb:${TAG}
    container_name: ${PREFIX}mongodb
    ports:
      - "27019:27017"
    networks:
      - robot-shop
  redis:
    image: redis:4.0.6
    container_name: ${PREFIX}redis
    ports:
      - "6381:6379"
    networks:
      - robot-shop
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    container_name: ${PREFIX}rabbitmq
    networks:
      - robot-shop
  catalogue:
    # build:
    #   context: serverless-catalogue
    image: ${REPO}/rs-catalogue:${TAG}
    container_name: ${PREFIX}catalogue
    depends_on:
      - mongodb
    networks:
      - robot-shop
  user:
    # build:
    #   context: serverless-user
    image: ${REPO}/rs-user:${TAG}
    container_name: ${PREFIX}user
    depends_on:
      - mongodb
      - redis
    networks:
      - robot-shop
  cart:
    # build:
    #   context: serverless-cart
    image: ${REPO}/rs-cart:${TAG}
    container_name: ${PREFIX}cart
    depends_on:
      - redis
    networks:
      - robot-shop
  mysql:
    # build:
    #   context: serverless-mysql
    image: ${REPO}/rs-mysql-db:${TAG}
    container_name: ${PREFIX}mysql
    ports:
      - "3306:3306"
    cap_add:
      - NET_ADMIN
    networks:
      - robot-shop
  shipping:
    # build:
    #   context: serverless-shipping
    image: ${REPO}/rs-shipping:${TAG}
    container_name: ${PREFIX}shipping
    depends_on:
      - mysql
    networks:
      - robot-shop
  ratings:
    # build:
    #   context: serverless-ratings
    image: ${REPO}/rs-ratings:${TAG}
    container_name: ${PREFIX}ratings
    networks:
      - robot-shop
    depends_on:
      - mysql
  payment:
    # build:
    #   context: serverless-payment
    image: ${REPO}/rs-payment:${TAG}
    container_name: ${PREFIX}payment
    depends_on:
      - rabbitmq
    networks:
      - robot-shop
    # Uncomment to change payment gateway
    #environment:
      #PAYMENT_GATEWAY: "https://www.worldpay.com"
  dispatch:
    # build:
    #   context: serverless-dispatch
    image: ${REPO}/rs-dispatch:${TAG}
    container_name: ${PREFIX}dispatch
    depends_on:
      - rabbitmq
    networks:
      - robot-shop
  web:
    # build:
    #   context: serverless-web
    image: ${REPO}/rs-web:${TAG}
    container_name: ${PREFIX}web
    depends_on:
      - catalogue
      - user
      - shipping
      - payment
    ports:
      - "8080:8080"
      - "8079:8079"
    networks:
      - robot-shop
    # Uncomment to enable Instana EUM
    # environment:
      # INSTANA_EUM_KEY: <your eum key>
      # INSTANA_EUM_REPORTING_URL: https://eum-us-west-2.instana.io
      # INSTANA_EUM_REPORTING_URL: https://eum-eu-west-1.instana.io

networks:
  robot-shop:

